[package]
name = "skl"
version = "0.1.1"
edition = "2021"
repository = "https://github.com/al8n/skl-rs"
description = "A placeholder"
license = "MIT/Apache-2.0"

[[bench]]
path = "benches/foo.rs"
name = "foo"
harness = false

[features]
default = ["std"]
alloc = []
std = ["kvstructs/std", "rand/std", "rand/std_rng", "inline_more", "crossbeam-epoch/default", "parking_lot"]
inline_more = []
js = ["getrandom/js"]

[target.'cfg(loom)'.dependencies]
loom = "0.5.6"

[dependencies]
crossbeam-epoch = { version = "0.9", default-features = false }
crossbeam-utils = { version = "0.8", default-features = false }
getrandom = { version = "0.2", optional = true }
parking_lot = { version = "0.12", optional = true }
kvstructs = { version = "0.0.23", default-features = false }
rand = { version = "0.8", default-features = false, features = ["getrandom"] }
spin = { version = "0.9", default-features = false, features = ["spin_mutex"] }

[dev-dependencies]
criterion = "0.3"
tempfile = "3"
parking_lot = "0.12"

[profile.bench]
opt-level = 3
debug = false
codegen-units = 1
lto = 'thin'
incremental = false
debug-assertions = false
overflow-checks = false
rpath = false



[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
