name: CI

on:
  push:
    # Ignore bors branches, since they are covered by `clippy_bors.yml`
    branches:
      - main
    # Don't run Clippy tests, when only textfiles were modified
    paths-ignore:
      - "README"
      - "COPYRIGHT"
      - "LICENSE-*"
      - "**.md"
      - "**.txt"
  pull_request:
    # Don't run Clippy tests, when only textfiles were modified
    paths-ignore:
      - "README"
      - "COPYRIGHT"
      - "LICENSE-*"
      - "**.md"
      - "**.txt"

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1
  nightly: nightly-2022-06-27
  stable: stable

defaults:
  run:
    shell: bash

jobs:
  # Check formatting
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      run: rustup update stable && rustup default stable
    - name: Check formatting
      run: cargo fmt --all -- --check

  # Apply clippy lints
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Apply clippy lints
      run: cargo clippy --all-features

  # This represents the minimum Rust version supported by
  # Bytes. Updating this should be done in a dedicated PR.
  #
  # Tests are not run as tests may require newer versions of
  # rust.
  minrust:
    name: minrust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup update 1.62.0 && rustup default 1.62.0
      - name: Check
        run: . ci/test-stable.sh check

  # Stable
  stable:
    name: stable
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        # --no-self-update is necessary because the windows environment cannot self-update rustup.exe.
        run: rustup update stable --no-self-update && rustup default stable
      - name: Test
        run: . ci/test-stable.sh test

 # Nightly
  nightly:
    name: nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup update $nightly && rustup default $nightly
      - name: Test
        run: . ci/test-stable.sh test

  # Sanitizers
  sanitizer:
    name: sanitizer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup update $nightly && rustup default $nightly
      - name: Install rust-src
        run: rustup component add rust-src
      - name: ASAN / LSAN / TSAN
        run: . ci/sanitizer.sh

  # valgrind
  valgrind:
    name: valgrind
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust ${{ env.stable }}
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ env.stable }}
            override: true
      - uses: Swatinem/rust-cache@v1

      - name: Install Valgrind
        run: |
          sudo apt-get update -y
          sudo apt-get install -y valgrind
      # Compile tests
      - name: cargo build test-fixed
        run: cargo build --bin test-fixed
        working-directory: integration

      # Run with valgrind
      - name: Run valgrind test-fixed
        run: valgrind --error-exitcode=1 --leak-check=full --show-leak-kinds=all ./target/debug/test-fixed

      # Compile tests
      - name: cargo build test-epoch
        run: cargo build --bin test-epoch
        working-directory: integration

      # Run with valgrind
      - name: Run valgrind test-epoch
        run: valgrind --error-exitcode=1 --leak-check=full --show-leak-kinds=all ./target/debug/test-epoch

  # TODO: fix miri tests
  # miri:
  #   name: miri
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install Rust ${{ env.rust_nightly }}
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: ${{ env.rust_nightly }}
  #         components: miri
  #         override: true
  #     - uses: Swatinem/rust-cache@v1
  #     - name: miri
  #       run: cargo miri test --all-features --lib
  #       env:
  #         MIRIFLAGS: -Zmiri-disable-isolation -Zmiri-tag-raw-pointers
  #         PROPTEST_CASES: 10

  tarpaulin:
    name: cargo tarpaulin
    runs-on: ubuntu-latest
    needs: 
      - rustfmt
      - clippy
      - stable
      - nightly
      - sanitizer
      - valgrind
    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/tarpaulin@v0.1
      - name: Run cargo tarpaulin
        run: cargo tarpaulin --all-features --run-types Tests,Doctests --out Xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: file

  
